const express = require('express');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const { v4: uuidv4 } = require('uuid');
const config = require('../config');
const { register, lookup } = require('../storage');

const router = express.Router();

// Ensure upload directory exists at startup (outside web root)
fs.mkdirSync(config.uploadDir, { recursive: true });

// Multer stores files under UUID names in the secure upload directory.
// The directory is a sibling of public/, never inside it.
const storage = multer.diskStorage({
  destination(_req, _file, cb) {
    cb(null, config.uploadDir);
  },
  filename(_req, _file, cb) {
    // Use UUID as the on-disk name so the original name is never guessable.
    cb(null, `${uuidv4()}.pdf`);
  },
});

function pdfFilter(_req, file, cb) {
  const allowedMime = 'application/pdf';
  const allowedExt = '.pdf';
  const ext = path.extname(file.originalname).toLowerCase();
  if (file.mimetype !== allowedMime || ext !== allowedExt) {
    return cb(Object.assign(new Error('Only PDF files are accepted'), { status: 415 }));
  }
  cb(null, true);
}

const upload = multer({
  storage,
  fileFilter: pdfFilter,
  limits: { fileSize: config.maxFileSize },
});

/**
 * POST /api/files/upload
 * Accepts a single PDF form-field named "file".
 * Returns a download token; the actual file path is never exposed.
 */
router.post('/upload', upload.single('file'), (req, res) => {
  if (!req.file) {
    return res.status(400).json({ error: 'No file provided' });
  }

  const token = uuidv4();
  register(token, {
    storedName: req.file.filename,
    originalName: req.file.originalname,
    mimeType: req.file.mimetype,
  });

  return res.status(201).json({
    message: 'File uploaded successfully',
    downloadUrl: `/api/files/download/${token}`,
  });
});

/**
 * GET /api/files/download/:token
 * Resolves the token to a stored file and streams it to the client.
 * The file path is never exposed; path traversal is impossible because
 * storedName is always a UUID.pdf set by our own filename callback.
 */
router.get('/download/:token', (req, res) => {
  const meta = lookup(req.params.token);
  if (!meta) {
    return res.status(404).json({ error: 'File not found' });
  }

  // Build the absolute path from config.uploadDir + UUID filename.
  // path.join will normalise the path; since storedName is always a UUID.pdf
  // generated by us, path traversal via the token is not possible.
  const filePath = path.join(config.uploadDir, meta.storedName);

  if (!fs.existsSync(filePath)) {
    return res.status(404).json({ error: 'File not found' });
  }

  res.setHeader('Content-Type', meta.mimeType);
  res.setHeader(
    'Content-Disposition',
    `attachment; filename="${encodeURIComponent(meta.originalName)}"`,
  );
  res.sendFile(filePath);
});

// Multer error handler
router.use((err, _req, res, _next) => {
  if (err instanceof multer.MulterError) {
    return res.status(413).json({ error: err.message });
  }
  if (err && err.status) {
    return res.status(err.status).json({ error: err.message });
  }
  res.status(500).json({ error: 'Internal server error' });
});

module.exports = router;
